table dim_account
	lineageTag: 0264016d-970f-4f4e-bcfa-299d6a882280

	column AccountKey
		dataType: int64
		formatString: 0
		lineageTag: 3fd62fcd-e915-4703-b1bd-52c21fba41ee
		summarizeBy: none
		sourceColumn: AccountKey

		annotation SummarizationSetBy = Automatic

	column Account
		dataType: string
		lineageTag: e04d541c-0541-4ca7-869e-d803a87ed7a9
		summarizeBy: none
		sourceColumn: Account
		sortByColumn: StatementSort

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 5c09ef3d-90eb-4ba4-ae93-a2ee493ea7e4
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 4186ac91-d301-4591-aeb4-24675ce9fcb9
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Sign
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 32a70a76-4307-433a-aa4b-1d9605bc46cc
		summarizeBy: none
		sourceColumn: Sign

		annotation SummarizationSetBy = User

	column StatementSort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 09463a22-0533-4406-a7c8-a7108239d2a1
		summarizeBy: none
		sourceColumn: StatementSort

		annotation SummarizationSetBy = User

	partition dim_account = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Lenovo\Desktop\portfolio\Migrate to Middle east\Sulaiman Ahmed Linkedin Profile Optimization\Power BI Design Language Blog\POC\data\dim_account.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"AccountKey", Int64.Type}, {"Account", type text}, {"Category", type text}, {"Subcategory", type text}, {"Sign", Int64.Type}, {"StatementSort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

