table fact_pnl_budget
	lineageTag: c179f421-eae1-4231-b979-bc6eeb14ca9f

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 30a4239d-477a-4c5a-8fad-364803bd453c
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 3c34ae3a-bb18-485d-b621-993fa24eeebf
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column AccountKey
		dataType: int64
		formatString: 0
		lineageTag: 7aea543f-3a3c-4c1c-9e97-1b7286c17b2c
		summarizeBy: none
		sourceColumn: AccountKey

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: 03a73828-fa9d-4fc4-9764-53dcfdf2377a
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	partition fact_pnl_budget = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Lenovo\Desktop\portfolio\Migrate to Middle east\Sulaiman Ahmed Linkedin Profile Optimization\Power BI Design Language Blog\POC\data\fact_pnl_budget.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"StoreKey", Int64.Type}, {"AccountKey", Int64.Type}, {"Amount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

